name: run MDTF tests on ParallelWorks cloud platform
  
on:
  push:
    branches:
      - main
      - develop
      - add_docker_image
  pull_request:
    branches:
      - main
      - develop
jobs:
     ParallelWorks:
           runs-on: [pw-platform]
           steps:
               # - name: Spinning up cluster
               #   run: python3 /home/Jessica.Liptak/pw/storage/mdtf/MDTF-diagnostics/cloud_scripts/startClusters.py gcluster_noaa
                - name: Turn off cluster
                  run: python3 /home/Jessica.Liptak/pw/storage/mdtf/MDTF-diagnostics/cloud_scripts/stopClusters.py gcluster_noaa
